[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # see https://docs.astral.sh/ruff/rules/
    ######################################## 
    # pycodestyle
    # - Removing multiple spaces (prevents alignment)
    "E221",
    "E222",
    "E241",
    "E271",
    "E272",
    ######################################## 
    # pydocstyle
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D105",  # Missing docstring in magic method
    "D107",  # Missing docstring in __init__
    "D203",  # One blank line before class docstring
    "D213",  # Multi-line summary second line
    ######################################## 
    # Security (flake8-bandit)
    "S101", # Use of assert detected
    "S311", # Standard pseudo-random generators are not suitable for cry
    ######################################## 
    # Miscellaneous
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "EM102",  # Exception must not use an f-string literal
    "ERA001", # Commented out code
    "FA102",  # Missing `from __future__ import annotations`, but uses PEP 585 collection
    "FIX002", # TODO comment
    "TD002",  # Missing author
    "TD003",  # Missing issue link on the line following this TODO
    "TRY003", # Avoid specifying long messages outside the exception class
]

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.ruff.lint.isort]
# import-heading-stdlib = "Standard library"
# import-heading-thirdparty = "3rd party"
# import-heading-firstparty = "1st party"
# import-heading-localfolder = "Local"
force-sort-within-sections = true
#multi-line-output = 3
